os: osx
osx_image: xcode10.1
language: swift
sudo: required
install:
    - wget https://swift.org/builds/swift-5.0.1-release/xcode/swift-5.0.1-RELEASE/swift-5.0.1-RELEASE-osx.pkg
    - sudo installer -pkg swift-5.0.1-RELEASE-osx.pkg -target /
    - export PATH="/Library/Developer/Toolchains/swift-5.0.1-RELEASE.xtoolchain/usr/bin:$PATH"
script:
    - bash scripts/test_challenges.sh
